---
"$schema": http://api.nexus/schema/draft-01#
goPackage: gen
services:
  - identifier: UserService
    name: directory.UserService
    description: Service for managing users.
    operations:
      - identifier: getUser
        name: Get User
        description: Retrieves a user by their ID.
        input:
          "$ref": "#definitions/getPersonRequest"
        output:
          "$ref": "#definitions/getPersonResponse"
definitions:
  person:
    title: Person
    description: A simple person schema
    type: object
    properties:
      id:
        description: The person's identifier
        type: string
      name:
        description: The person's name
        type: string
      age:
        description: The person's age
        type: integer
        minimum: 0
      email:
        description: The person's email address
        type: string
        format: email
    required:
      - id
      - name
      - age
  getPersonRequest:
    title: GetPersonRequest
    description: Request to retrieve a person by their user ID.
    type: object
    properties:
      userId:
        type: string
        description: The unique identifier of the user.
    required:
      - userId
  getPersonResponse:
    title: GetPersonResponse
    description: Response containing person details.
    "$ref": "#/definitions/person"
